- hosts: ansibletest
  tasks:
    - name: Ping site
      shell: ping -c 1 -w 2 {{ target }}
      register: ping_result

    - name: Ping result
      debug:
        msg: "{{ ping_result.stdout_lines }}"
