- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: upgrade_result

- name: Upgrade result
  debug:
    msg: "{{ upgrade_result.stdout_lines }}"

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
