- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: upgrade_result

- name: Upgrade result
  debug:
    msg: "{{ upgrade_result.stdout_lines }}"

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Run the equivalent of "apt-get clean" as a separate step
  ansible.builtin.apt:
    clean: yes
