---
# file: roles/docker/tasks/main.yml

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "localadmin"
    groups: docker
    append: yes

- name: Install Python pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker Compose using pip
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Create project directory
  ansible.builtin.file:
    path: /opt/test-hello-world
    state: directory
    mode: '0755'

- name: Download docker-compose.yml from GitHub
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jimmydoh/ansibletest/main/roles/docker/files/hello-docker-compose.yml
    dest: /opt/test-hello-world/docker-compose.yml
    mode: '0644'

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/test-hello-world
    state: present
  register: compose_result

- name: Show compose deployment result
  ansible.builtin.debug:
    msg: "{{ compose_result }}"
